import { Product, Testimony } from "@utils/types";

export const testimonies: Testimony[] = [
  {
    name: "Sophia Johnson",
    star: 4.8,
    comment:
      "The coffee is amazing and the muffins are to die for! A perfect place to relax and enjoy a book.",
    imgUrl: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    name: "Liam Smith",
    star: 4.9,
    comment:
      "I love working here! The WiFi is super fast and the ambiance is cozy. Highly recommend!",
    imgUrl: "https://randomuser.me/api/portraits/men/34.jpg",
  },
  {
    name: "Olivia Brown",
    star: 4.7,
    comment:
      "Such a charming spot with great coffee and an impressive collection of books. Perfect for a rainy day.",
    imgUrl: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Noah Jones",
    star: 5.0,
    comment:
      "Best coffee shop in town! The muffins are always fresh and the atmosphere is perfect for reading or working.",
    imgUrl: "https://randomuser.me/api/portraits/men/58.jpg",
  },
  {
    name: "Emma Garcia",
    star: 4.6,
    comment:
      "Great coffee and a cozy place to read. The WiFi is reliable for working online too.",
    imgUrl: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Lucas Martinez",
    star: 4.5,
    comment:
      "I always enjoy my time here. The muffins are delicious and the coffee is top-notch.",
    imgUrl: "https://randomuser.me/api/portraits/men/76.jpg",
  },
  {
    name: "Ava Lee",
    star: 4.9,
    comment:
      "This is my go-to spot for a good read and a great cup of coffee. Highly recommend the muffins too!",
    imgUrl: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    name: "Mason Davis",
    star: 4.7,
    comment:
      "A perfect blend of good coffee, delicious muffins, and a relaxing atmosphere. I love working from here.",
    imgUrl: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    name: "Isabella Rodriguez",
    star: 4.8,
    comment:
      "A cozy and welcoming place with great coffee. The book collection is a bonus!",
    imgUrl: "https://randomuser.me/api/portraits/women/63.jpg",
  },
  {
    name: "Elijah Wilson",
    star: 4.5,
    comment:
      "The WiFi is strong and the coffee is even stronger! A great place to work and relax.",
    imgUrl: "https://randomuser.me/api/portraits/men/85.jpg",
  },
  {
    name: "Mia Anderson",
    star: 4.7,
    comment:
      "I love the cozy vibe here. The coffee and muffins are always on point, and there's a great selection of books.",
    imgUrl: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    name: "James Thompson",
    star: 4.8,
    comment:
      "This place has it all—great coffee, delicious muffins, and a perfect atmosphere for reading or working.",
    imgUrl: "https://randomuser.me/api/portraits/men/92.jpg",
  },
  {
    name: "Amelia White",
    star: 4.9,
    comment:
      "A lovely spot with a fantastic book collection and the best coffee around. The muffins are a must-try!",
    imgUrl: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    name: "Benjamin Harris",
    star: 4.6,
    comment:
      "Great atmosphere for working or just relaxing with a book. The coffee and muffins are excellent.",
    imgUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Evelyn Clark",
    star: 4.8,
    comment:
      "The perfect place to unwind with a cup of coffee and a good book. The WiFi is also very reliable.",
    imgUrl: "https://randomuser.me/api/portraits/women/47.jpg",
  },
  {
    name: "Alexander Lewis",
    star: 5.0,
    comment:
      "I come here to work often. The coffee is great, the WiFi is fast, and the muffins are delicious.",
    imgUrl: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Charlotte Walker",
    star: 4.7,
    comment:
      "A cozy, welcoming spot with amazing coffee and a great selection of books. Perfect for any coffee lover.",
    imgUrl: "https://randomuser.me/api/portraits/women/38.jpg",
  },
  {
    name: "Jack Young",
    star: 4.9,
    comment:
      "A wonderful place to work or just enjoy a good book. The coffee and muffins are always fresh and delicious.",
    imgUrl: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    name: "Grace Hall",
    star: 4.8,
    comment:
      "This coffee shop is my favorite. Great coffee, yummy muffins, and a cozy place to read and relax.",
    imgUrl: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    name: "William Allen",
    star: 4.6,
    comment:
      "Fantastic place to enjoy a cup of coffee while working online. The atmosphere is perfect for productivity.",
    imgUrl: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    name: "Ella King",
    star: 4.7,
    comment:
      "Great coffee, lovely muffins, and a cozy place to enjoy a book or get some work done. I love coming here!",
    imgUrl: "https://randomuser.me/api/portraits/women/75.jpg",
  },
];

export const products: Product[] = [
  {
    product_id: 3,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Espresso Beans",
    product: "Espresso Roast",
    product_description: "Our house blend for a good espresso shot.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 11.8,
    current_retail_price: "$14.75",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_07dacdb1.png",
  },
  {
    product_id: 4,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Espresso Beans",
    product: "Primo Espresso Roast",
    product_description: "Our primium single source of hand roasted beans.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 16.36,
    current_retail_price: "$20.45",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_f914f1cd.jpg",
  },

  {
    product_id: 87,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Ouro Brasileiro shot",
    product_description: "From Rio",
    unit_of_measure: "1.5 oz",
    current_wholesale_price: 0.6,
    current_retail_price: "$3.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_d07aaf8a.jpg",
  },
  {
    product_id: 88,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Ouro Brasileiro shot promo",
    product_description: "Ouro promo",
    unit_of_measure: "16 oz",
    current_wholesale_price: 0.42,
    current_retail_price: "$2.10",
    tax_exempt_yn: "Y",
    promo_yn: "Y",
    new_product_yn: "N",
    imgUrl: "img_2590b538.jpg",
  },

  {
    product_id: 40,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Cappuccino",
    product_description:
      "You will think you are in Venice when you sip this one.",
    unit_of_measure: "1.5 oz",
    current_wholesale_price: 0.75,
    current_retail_price: "$3.75",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",

    imgUrl: "img_5802f7ca.png",
  },
  {
    product_id: 41,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Cappuccino Lg",
    product_description:
      "You will think you are in Venice when you sip this one.",
    unit_of_measure: "3.0 oz",
    current_wholesale_price: 0.85,
    current_retail_price: "$4.25",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_7a503d72.png",
  },

  {
    product_id: 38,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Latte",
    product_description:
      "You will think you are in Venice when you sip this one.",
    unit_of_measure: "1.5 oz",
    current_wholesale_price: 0.75,
    current_retail_price: "$3.75",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_837eb47d.jpg",
  },
  {
    product_id: 39,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Barista Espresso",
    product: "Latte Rg",
    product_description:
      "You will think you are in Venice when you sip this one.",
    unit_of_measure: "3.0 oz",
    current_wholesale_price: 0.85,
    current_retail_price: "$4.25",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_a82e9d9d.png",
  },

  {
    product_id: 1,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Organic Beans",
    product: "Brazilian - Organic",
    product_description: "It's like Carnival in a cup. Clean and smooth.",
    unit_of_measure: "12 oz",
    current_wholesale_price: 14.4,
    current_retail_price: "$18.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_e30987ab.png",
  },
  {
    product_id: 2,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "House blend Beans",
    product: "Our Old Time Diner Blend",
    product_description:
      "Out packed blend of beans that is reminiscent of the cup of coffee you used to get at a diner.",
    unit_of_measure: "12 oz",
    current_wholesale_price: 14.4,
    current_retail_price: "$18.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_0a87abf0.png",
  },
  {
    product_id: 5,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Gourmet Beans",
    product: "Columbian Medium Roast",
    product_description: "A smooth cup of coffee any time of day.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 12,
    current_retail_price: "$15.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_a778383c.png",
  },
  {
    product_id: 6,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Gourmet Beans",
    product: "Ethiopia",
    product_description: "From the home of coffee.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 16.8,
    current_retail_price: "$21.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_3bdbaa59.png",
  },
  {
    product_id: 7,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Premium Beans",
    product: "Jamacian Coffee River",
    product_description: "Ya man, it will start your day off right.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 15.8,
    current_retail_price: "$19.75",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_6a936bf1.png",
  },
  {
    product_id: 8,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Premium Beans",
    product: "Civet Cat",
    product_description:
      "The most expensive coffee in the world, the cats do all the work.",
    unit_of_measure: ".5 lb",
    current_wholesale_price: 36,
    current_retail_price: "$45.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_7cb77e48.png",
  },

  {
    product_id: 9,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Organic Beans",
    product: "Organic Decaf Blend",
    product_description:
      "Our blend of hand picked organic beans that have been naturally decaffinated.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 18,
    current_retail_price: "$22.50",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_8ed5223a.png",
  },
  {
    product_id: 10,
    product_group: "Whole Bean/Teas",
    product_category: "Coffee beans",
    product_type: "Green beans",
    product: "Guatemalan Sustainably Grown",
    product_description: "Green beans you can roast yourself.",
    unit_of_measure: "1 lb",
    current_wholesale_price: 8,
    current_retail_price: "$10.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_bc051933.jpg",
  },
  {
    product_id: 11,
    product_group: "Whole Bean/Teas",
    product_category: "Loose Tea",
    product_type: "Herbal tea",
    product: "Lemon Grass",
    product_description:
      "You will think you are Thailand as you sip your cuppa.",
    unit_of_measure: ".9 oz",
    current_wholesale_price: 7.16,
    current_retail_price: "$8.95",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_e5d98a5d.png",
  },

  {
    product_id: 85,
    product_group: "Beverages",
    product_category: "Coffee",
    product_type: "Specialty coffee",
    product: "Rio Nights",
    product_description: "2 shots of Ouro Brasilerio and pure cane sugar syrup",
    unit_of_measure: "6 oz",
    current_wholesale_price: 1.2,
    current_retail_price: "$6.00",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "Y",
    imgUrl: "img_0f55dcad.jpg",
  },

  {
    product_id: 58,
    product_group: "Beverages",
    product_category: "Drinking Chocolate",
    product_type: "Hot chocolate",
    product: "Dark chocolate Rg",
    product_description: "Slightly bitter, but still very rich.",
    unit_of_measure: "12 oz",
    current_wholesale_price: 2.63,
    current_retail_price: "$3.50",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_49733633.jpg",
  },

  {
    product_id: 60,
    product_group: "Beverages",
    product_category: "Drinking Chocolate",
    product_type: "Hot chocolate",
    product: "Sustainably Grown Organic Rg",
    product_description: "Just pure notes of spice.",
    unit_of_measure: "12 oz",
    current_wholesale_price: 2.81,
    current_retail_price: "$3.75",
    tax_exempt_yn: "Y",
    promo_yn: "N",
    new_product_yn: "N",
    imgUrl: "img_6ea0ffcf.png",
  },
];
